name: pingme
description: "Floating reminder overlay app with glassmorphism design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_overlay_window: ^0.4.3
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  permission_handler: ^11.1.0
  provider: ^6.1.1
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  intl: ^0.20.2

  # Background scheduling
  android_alarm_manager_plus: ^4.0.4
  flutter_local_notifications: ^18.0.1
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
